import { resolve } from 'node:path'

import { loadWorkflowFile } from '../core/loader.js'
import type { DraftWorkflow } from './common.js'
import { toKebabCase } from './common.js'

export const generateDraftFromWorkflow = async ({
  cwd,
  workflowPath
}: {
  cwd: string
  workflowPath: string
}): Promise<DraftWorkflow> => {
  const resolvedPath = resolve(cwd, workflowPath)
  const workflow = await loadWorkflowFile({
    path: resolvedPath
  })
  const draftName = workflow.name.endsWith('-draft') ? workflow.name : `${workflow.name}-draft`

  return {
    comments: [
      'Generated by BugScrub.',
      `Source: workflow ${workflowPath}`,
      `Cloned from existing workflow "${workflow.name}". Review surface/capability/assertion refs before use.`
    ],
    fileName: `${toKebabCase({
      value: draftName
    })}.yaml`,
    workflow: {
      ...workflow,
      name: draftName
    }
  }
}
