import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { join } from 'node:path'

// Diff-backed generation maps changed files to routes or existing surfaces.
import type { SurfaceBundle } from '../core/loader.js'
import type { BugScrubConfig } from '../types/index.js'
import { CliError } from '../utils/errors.js'
import type { DraftWorkflow } from './common.js'
import {
  buildDraftFromRoute,
  buildDraftFromSurface,
  extractRoutesFromFile,
  listRepoFiles
} from './common.js'

const execFileAsync = promisify(execFile)

export type DiffMode =
  | { kind: 'local' }
  | { kind: 'main' }
  | { baseBranch: string; kind: 'branch' }

const getDiffCommandArgs = ({
  mode
}: {
  mode: DiffMode
}): string[] => {
  if (mode.kind === 'local') {
    return ['diff', '--name-only', 'HEAD', '--']
  }

  if (mode.kind === 'main') {
    return ['diff', '--name-only', 'main...HEAD', '--']
  }

  return ['diff', '--name-only', `${mode.baseBranch}...HEAD`, '--']
}

const getSourceLabel = ({
  mode
}: {
  mode: DiffMode
}): string => {
  if (mode.kind === 'local') {
    return 'current local changes'
  }

  if (mode.kind === 'main') {
    return 'compare current branch to main'
  }

  return `compare current branch to ${mode.baseBranch}`
}

const loadChangedFiles = async ({
  cwd,
  mode
}: {
  cwd: string
  mode: DiffMode
}): Promise<string[]> => {
  try {
    const { stdout } = await execFileAsync('git', getDiffCommandArgs({ mode }), {
      cwd
    })

    return stdout
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)
      .sort((left, right) => left.localeCompare(right))
  } catch (error) {
    throw new CliError({
      message:
        error instanceof Error
          ? `Unable to read git diff for generate: ${error.message}`
          : 'Unable to read git diff for generate.',
      exitCode: 1
    })
  }
}

export const generateDraftsFromDiff = async ({
  config,
  cwd,
  mode,
  surfaces
}: {
  config: BugScrubConfig
  cwd: string
  mode: DiffMode
  surfaces: SurfaceBundle[]
}): Promise<DraftWorkflow[]> => {
  const changedFiles = await loadChangedFiles({
    cwd,
    mode
  })

  if (changedFiles.length === 0) {
    throw new CliError({
      message: 'No changed files were found for the selected diff source.',
      exitCode: 1
    })
  }

  const routeDrafts = new Map<string, DraftWorkflow>()
  const surfaceDrafts = new Map<string, DraftWorkflow>()
  const knownFiles = new Set(
    await listRepoFiles({
      root: cwd
    })
  )

  for (const relativePath of changedFiles) {
    const surfaceMatch = relativePath.match(/^\.bugscrub\/surfaces\/([^/]+)\//)

    if (surfaceMatch) {
      const existingSurface = surfaces.find(
        (surface) => surface.surface.name === surfaceMatch[1]
      )

      if (existingSurface) {
        surfaceDrafts.set(
          existingSurface.surface.name,
          buildDraftFromSurface({
            comments: [
              'Generated by BugScrub.',
              `Source: ${getSourceLabel({ mode })}`
            ],
            config,
            surface: existingSurface
          })
        )
      }

      continue
    }

    if (knownFiles.has(relativePath)) {
      const extractedRoutes = await extractRoutesFromFile({
        path: join(cwd, relativePath),
        relativePath
      })

      for (const route of extractedRoutes) {
        routeDrafts.set(
          route,
          buildDraftFromRoute({
            comments: [
              'Generated by BugScrub.',
              `Source: ${getSourceLabel({ mode })}`
            ],
            config,
            route,
            surfaces
          })
        )
      }
    }
  }

  const drafts = [...surfaceDrafts.values(), ...routeDrafts.values()]

  if (drafts.length === 0) {
    throw new CliError({
      message: 'No route or surface hints could be inferred from the selected diff source.',
      exitCode: 1
    })
  }

  return drafts.sort((left, right) => left.fileName.localeCompare(right.fileName))
}
