import type { SurfaceBundle } from '../core/loader.js'
import type { BugScrubConfig } from '../types/index.js'
import type { DraftWorkflow } from './common.js'
import { buildDraftFromRoute } from './common.js'

export const generateDraftFromRoute = ({
  config,
  route,
  surfaces
}: {
  config: BugScrubConfig
  route: string
  surfaces: SurfaceBundle[]
}): DraftWorkflow => {
  return buildDraftFromRoute({
    comments: [
      'Generated by BugScrub.',
      `Source: route ${route}`
    ],
    config,
    route,
    surfaces
  })
}
