import { join } from 'node:path'

// Test-backed generation extracts route hints and turns them into exploratory drafts.
import { detectProject } from '../init/detector.js'
import { CliError } from '../utils/errors.js'
import type { SurfaceBundle } from '../core/loader.js'
import type { BugScrubConfig } from '../types/index.js'
import type { DraftWorkflow } from './common.js'
import {
  buildDraftFromRoute,
  extractRoutesFromFile,
  isTestFile,
  listRepoFiles,
  toSurfaceName
} from './common.js'

const inferRouteFromTestPath = ({
  relativePath
}: {
  relativePath: string
}): string | undefined => {
  const normalized = relativePath
    .replace(/\\/g, '/')
    .replace(/\.(?:spec|test)\.[cm]?[jt]sx?$/i, '')
    .replace(/^tests?\//, '')
    .replace(/^e2e\//, '')
  const segments = normalized.split('/').filter(Boolean)
  const fileStem = segments.at(-1)

  if (!fileStem || fileStem === 'index') {
    return undefined
  }

  return `/${toSurfaceName({
    route: fileStem
  }).replace(/_/g, '-')}`
}

export const generateDraftsFromTests = async ({
  config,
  cwd,
  surfaces
}: {
  config: BugScrubConfig
  cwd: string
  surfaces: SurfaceBundle[]
}): Promise<DraftWorkflow[]> => {
  const detection = await detectProject({
    root: cwd
  })

  if (detection.testRunners.length === 0) {
    throw new CliError({
      message: 'No supported test runner was detected for `generate` from tests.',
      exitCode: 1
    })
  }

  const files = await listRepoFiles({
    root: cwd
  })
  const testFiles = files.filter((file) => isTestFile({ relativePath: file }))
  const routes = new Set<string>()

  for (const relativePath of testFiles) {
    const extracted = await extractRoutesFromFile({
      path: join(cwd, relativePath),
      relativePath
    })

    for (const route of extracted) {
      routes.add(route)
    }

    if (extracted.length === 0) {
      const fallback = inferRouteFromTestPath({
        relativePath
      })

      if (fallback) {
        routes.add(fallback)
      }
    }
  }

  if (routes.size === 0) {
    throw new CliError({
      message: 'No route hints were found in the detected test files.',
      exitCode: 1
    })
  }

  return [...routes].sort().map((route) =>
    buildDraftFromRoute({
      comments: [
        'Generated by BugScrub.',
        `Source: tests (${detection.testRunners.join(', ')})`
      ],
      config,
      route,
      surfaces
    })
  )
}
